import { sql } from 'drizzle-orm'
import { customType, timestamp, uuid } from 'drizzle-orm/pg-core'

/** UUID primary key generated by Postgres. */
export const id = () =>
  uuid()
    .primaryKey()
    .default(sql`gen_random_uuid()`)

/** created_at / updated_at on every table, stored as UTC timestamptz. */
export const timestamps = {
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdateFn(() => new Date()),
}

/** Binary column (Postgres bytea) mapped to a Node Buffer. */
export const bytea = customType<{ data: Buffer; driverData: Buffer }>({
  dataType: () => 'bytea',
})
